site_name: Vishwambhar Patil Notes
site_description: Personal Knowledge Base for Java, DSA, Spring Boot, and System Design
site_author: Vishwambhar Patil

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Optional: adds a "copy" button on code blocks (Material feature)
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md

  - Java:
      - JVM Internals: java/TOP-0 JVM Internals.md
      - Variable & Data Type: java/TOP-1 VAR_DATA_TYPE.md
      - Type Conversion & Casting: java/TOP-2 TYPE_CONVERSION_AND_CASTING.md
      - Operators: java/TOP-3 OPERATORS.md
      - Control Flow: java/TOP-4 CONTROL_FLOW.md
      - Modern Switch: java/TOP-5 MODERN_SWITCH.md
      - Methods & Stack Frames: java/TOP-6 METHODS_STACK_FRAMES.md
      - Method Overloading & Overriding: java/TOP-7 METHOD_OVERLOADING_OVERRIDING.md
      - Constructor: java/TOP-8 CONSTRUCTOR.md
      - Static vs Instance: java/TOP-9 STATIC_VS_INSTANCE.md
      - Final Keyword: java/TOP-10 FINAL_KEYWORD.md
      - Access Modifiers: java/TOP-11 ACCESS_MODIFIERS.md
      - Abstract Class vs Interface: java/TOP-12 ABSTRACT_CLASS_VS_INTERFACE.md
      - String / Builder / Buffer: java/TOP-13 STRING_STRING_BUILDER_AND_BUFFER.md
      - Collections Framework Part 1: java/TOP-14 COLLECTIONS_FRAMEWORK_1.md
      - Collections Framework Part 2: java/TOP-15 COLLECTIONS_FRAMEWORK_2.md

      - Multithreading (Part-1): java/TOP-16 Multithreading (Part-1).md
      - Multithreading (Part-2): java/TOP-17 Multithreading (Part-2).md
      - Multithreading (Part-3): java/TOP-18 Multithreading (Part-3).md
      - Exception Handling (Part-3): java/TOP-19 Exception Handling

  - DSA:
      - Overview: dsa/index.md

  - Spring Boot:
      - Overview: spring/index.md